name: Push Docker Image to ECR Public

on:
  push:
    branches:
      - main

jobs:
  push-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR Public
      run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

    - name: Build Docker image
      run: docker build -t docker-ecr .

    - name: Tag Docker image
      run: docker tag docker-ecr:latest public.ecr.aws/f6x5f0l3/docker-ecr:latest

    - name: Push Docker image to ECR Public
      run: docker push public.ecr.aws/f6x5f0l3/docker-ecr:latest
``
