name: Deploy Static Site to ECS
 
on:

  push:

    branches:

      - main
 
jobs:

  deploy:

    runs-on: ubuntu-latest
 
    steps:

    - name: Checkout code

      uses: actions/checkout@v3
 
    - name: Configure AWS credentials

      uses: aws-actions/configure-aws-credentials@v2

      with:

        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}

        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

        aws-region: us-east-1  # change to your region
 
    - name: Login to Amazon ECR

      id: login-ecr

      uses: aws-actions/amazon-ecr-login@v1
 
    - name: Build Docker image

      run: docker build -t static-site .
 
    - name: Tag Docker image

      run: docker tag static-site:latest public.ecr.aws/f6x5f0l3/docker-ecr/static-site:latest
 
    - name: Push Docker image to ECR

      run: docker push public.ecr.aws/f6x5f0l3/docker-ecr/static-site:latest
 
    - name: Deploy to ECS

      uses: aws-actions/amazon-ecs-deploy-task-definition@v1

      with:

        task-definition: ecs-task-def.json

        service: your-ecs-service-name

        cluster: your-ecs-cluster-name

        wait-for-service-stability: true

``
 
